#pragma once

#include "BluetoothSrv.h"
#include "CpuTemperatureSrv.h"
#include "ImseeAutoLightSrv.h"
#include "ImseeIrSrv.h"
#include "ImseeParamSrv.h"
#include "ImseeTxSrv.h"
#include "ImuFreqSrv.h"
#include "LaserCtrl.h"
#include "MemorySrv.h"
#include "SelfTest.h"
#include "SensorInit.h"
#include "SensorDeinit.h"
#include "SensorStart.h"
#include "SensorStop.h"
#include "SysTimeSrv.h"
#include "WifiConfigSrv.h"
#include "AudioSrv.h"
#include "AutoChargeSrv.h"
#include "SetLedSrv.h"
#include "SensorControl.h"
#include "SetStatusSrv.h"
#include "CabinControlSrv.h"

