rbn100:

  # config for ros_control of DiffDriveController

  # Publish all joint states -----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50

  # Velocity Controllers ---------------------------------------
  mobile_base_controller:
    type: diff_drive_controller/DiffDriveController
    left_wheel: left_wheel_joint
    right_wheel: right_wheel_joint
    publish_rate: 50
    pose_covariance_diagonal : [0.001, 0.001, 1000000.0, 1000000.0, 1000000.0, 1000.0]
    twist_covariance_diagonal: [0.001, 0.001, 1000000.0, 1000000.0, 1000000.0, 1000.0]
    # Odometry fused with IMU is published by robot_localization, so
    # no need to publish a TF based on encoders alone.
    enable_odom_tf: false
    # Husky hardware provides wheel velocities
    estimate_velocity_from_position: false
    # Wheel separation and diameter. These are both optional.
    # diff_drive_controller will attempt to read either one or both from the URDF if not specified as a parameter
    wheel_separation : 0.322
    wheel_radius : 0.0169
    wheel_separation_multiplier: 1.0 # default: 1.0
    wheel_radius_multiplier    : 1.0 # default: 1.0
    cmd_vel_timeout: 0.25
    base_frame_id: base_footprint #default: base_link
    # Whenever a min_* is unspecified, default to -max_*
    linear:
      x:
        has_velocity_limits    : true
        max_velocity           : 1.2  # m/s
        min_velocity           : -1.2 # m/s
        has_acceleration_limits: true
        max_acceleration       : 2.67  # m/s^2
        min_acceleration       : -2.67 # m/s^2
        has_jerk_limits        : false
        max_jerk               : 5.0  # m/s^3
    angular:
      z:
        has_velocity_limits    : true
        max_velocity           : 1.8  # rad/s
        has_acceleration_limits: true
        max_acceleration       : 1.5  # rad/s^2
        has_jerk_limits        : false
        max_jerk               : 2.5  # rad/s^3

  gazebo_ros_control:
    pid_gains:
      left_wheel_joint: {p: 100.0, i: 0.01, d: 10.0}
      right_wheel_joint: {p: 100.0, i: 0.01, d: 10.0}